### ISSUE TITLE
0x0aに対応する動詞

### ISSUE THREAD

**Issue by ryuichiueda** [amanoese/yukichant#1]
コマンドや文言をエンコードするときに改行コードが最後になることが多いので、現在「0x0A」に対応している「汚し」よりも、もっと決め台詞っぽいのがいいかななどと考えています。

いまTwitterで聞いたら、
「踊れ」「行使せよ」「歌え」「紡げ」「響け」（@I_am_Kanaiさんや@jiro_saburomaruさん）
などがありました。

アイデアだけですみませんがご検討くだされば幸いでっす。

**Comment by amanoese** [comment]
ありがとうございます！
https://github.com/amanoese/yukichant/pull/3 の修正にて 動詞の 「0x0A」は「命ず」に変更しました。

**Comment by amanoese** [comment]
「命ず」は微妙だったので、動詞の 「0x0A」は「具現化せよ」に変更しました。

**Comment by amanoese** [comment]
@jiro4989さんの https://github.com/amanoese/yukichant/pull/4 のPRにより動詞の「0x0A」は、  
["具現化せよ。", "踊れ。", "歌え。", "紡げ。"] からランダムに選ばれるようになりました。  
また、何か気になることがございましたらissuesであげていただけると幸いです。
