### ISSUE TITLE
コードに対応する名詞がないものがある

### ISSUE THREAD

**Issue by frodo821** [amanoese/yukichant#32]
`0xDF` に対応する名詞が定義されていないため、

```
$ echo "TV3[AoZE,hz" | chant
```

を実行するとクラッシュします。

https://github.com/amanoese/yukichant/blob/5e9d550be049b85628dae9fe890d3b287691d958/src/index.js#L31

**Comment by amanoese** [comment]
ご連絡ありがとうございます。
抜けてますね…
https://github.com/amanoese/yukichant/blob/5e9d550be049b85628dae9fe890d3b287691d958/data/meisi.json#L224-L225

**Comment by amanoese** [comment]
単語の抽出方法と合わせて、対応方法考えます

**Comment by amanoese** [comment]
https://github.com/amanoese/yukichant/pull/41 で対応済
